id: P05641C54
initial_creation_type: input
source_metadata:
  title: Saving Lives Series
  language: de
  description: 'The following texts are currently available as part of our Saving
    Lives series:'
  volume:
    c3ffcd7dcde7457897ddfa50ef8bff28:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    10cb332106f74e1f94f39f0101e92051:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Practices
    67d2e13fb8414adca36259745459de60:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Practices
    521e7c1652f74a9e987fd056398d3166:
      title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
        the Lives of Animals'
      parent: Practices
    504836b2b58b4b9e9c2fecb67dfeb572:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Practices
    c774c2566dd34913b9f6d811f62659a8:
      title: The Benefits of Saving Lives
      parent: Commentaries
created_at: '2022-03-01T05:42:44.272615'
last_modified_at: '2022-03-01T05:42:44.272618'
